variable "username" {
  
}

variable "admin_password" {
  
}

variable "url" {
  
}

variable "issuer" {
  
}

variable "company_name" {
  
}

variable "admin_email" {
  
}

variable "admin_first_name" {
  
}

variable "admin_last_name" {
  
}

variable "phone_number" {
    default = "000-000-0000"
}

variable "base_url" {
  
}

variable "ldaps_user" {
    default = "cn=administrator"
}

variable "ldaps_password" {
    default = ""
}